### PR TITLE
Add support for storage.conf,policy.json; fix user config support

### PR DESCRIPTION
**Pull request by richm**
Add support for storage.conf and policy.json
Fix user support - have to get user home dir and add that to paths
Separate config file testing to another test file - too difficult
to figure out which options will interfere with regular container
testing.

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
ok - ready for review

**Review by vrothberg — COMMENTED** [review]
LGTM

**Review by nhosoi — APPROVED** [review]
lgtm

**Pull request merged**
